name: Test, Build and Upload artifact

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8]
    name: Java ${{ matrix.java }} compile
    steps:
      - uses: actions/checkout@master

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - run: mvn -f pom.xml clean compile

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    needs: compile
    name: Java 8 build, deliver artifact and container
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Test and build project
        run: mvn -f pom.xml clean install

      - name: Show contents of the current working dir
        run: ls -la

      - name: Show contents of the target dir
        run: ls -la target

      - name: Upload Mavan build artifact
        uses: actions/upload-artifact@v1
        with:
          name: postgres-service-artifact.jar
          path: ./target/postgres-service-0.0.1-SNAPSHOT.jar

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build
        run: docker build -t ${{ secrets.DOCKER_USER }}/postgres-service:latest

      - name: Upload container to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/postgres-service:latest